name: fit_app
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  cloud_firestore: ^3.1.11
  cupertino_icons: ^1.0.2
  firebase_core: ^1.14.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.0.1
  flutter_lints: ^1.0.0
  freezed: ^1.1.1
  lottie: ^1.2.2
  youtube_player_flutter: ^8.0.0

dev_dependencies:
  build_runner: ^2.1.7
  flutter_launcher_icons: ^0.9.2
  flutter_test:
    sdk: flutter

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/cesar_fitness.jpeg"

flutter:

  uses-material-design: true
  assets:
    - assets/images/
    - assets/lottie_animations/
  fonts:
    - family: Dongle
      fonts:
        - asset: assets/fonts/Dongle-Light.ttf
        - asset: assets/fonts/Dongle-Regular.ttf
        - asset: assets/fonts/Dongle-Bold.ttf

    - family: RedHat
      fonts:
        - asset: assets/fonts/RedHatDisplay-Regular.ttf
        - asset: assets/fonts/RedHatDisplay-Medium.ttf
          weight: 500
        - asset: assets/fonts/RedHatDisplay-Bold.ttf
          weight: 700
        - asset: assets/fonts/RedHatDisplay-Black.ttf
          weight: 900
